#!/usr/bin/env python3
"""Emit test/host/vectors.h from test/vectors.json (C arrays + expectations).

The JSON is the ground truth produced by the unmodified Python library in
test/ref/hiflow_ble. This script only reshapes it into static C arrays; it
never recomputes crypto itself.

Usage:
    python3 test/emit_vectors_h.py [vectors.json] [out/vectors.h]
Defaults: <script_dir>/vectors.json  ->  <script_dir>/host/vectors.h
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


def c_bytes(name: str, data: bytes) -> str:
    """Emit `static const uint8_t name[..] = { .. };` (len != 0)."""
    n = len(data)
    if n == 0:
        return f"static const uint8_t {name}[1] = {{ 0x00 }}; /* length 0 */"
    body = ", ".join(f"0x{b:02x}" for b in data)
    return f"static const uint8_t {name}[{n}] = {{ {body} }};"


def emit(j: dict) -> str:
    out: list[str] = []
    ap = out.append

    ap("/* AUTO-GENERATED by test/emit_vectors_h.py from test/vectors.json.")
    ap(" * Ground truth: unmodified TheTiEr/hiflow-ble (test/ref/hiflow_ble).")
    ap(" * DO NOT EDIT BY HAND. */")
    ap("#ifndef HIFLOW_TEST_VECTORS_H")
    ap("#define HIFLOW_TEST_VECTORS_H")
    ap("")
    ap("#include <stddef.h>")
    ap("#include <stdint.h>")
    ap("")

    meta = j["meta"]
    sn = meta["sn"]
    enc_rand = bytes.fromhex(meta["enc_rand_hex"])

    ap(f'#define VEC_SN "{sn}"')
    ap(f'#define VEC_SN_LEN {len(sn)}')
    ap(f'#define VEC_SALT_V0 "{meta["salt_v0"]}"')
    ap(f'#define VEC_ENC_RAND_LEN {len(enc_rand)}')
    ap(c_bytes("VEC_ENC_RAND", enc_rand))
    ap("")

    # ---------- cmds ----------
    ap("/* command constants */")
    for k, v in j["cmds"].items():
        ap(f"#define VEC_CMD_{k.upper()} ((uint16_t){v})")
    ap("")

    # ---------- crc ----------
    ap("typedef struct {")
    ap("    const uint8_t *data;")
    ap("    size_t len;")
    ap("    uint16_t crc;")
    ap("} vec_crc_t;")
    ap("")
    crc_entries = []
    for i, c in enumerate(j["crc16_modbus"]):
        name = f"vec_crc{i}_data"
        data = bytes.fromhex(c["data_hex"])
        ap(c_bytes(name, data))
        crc_entries.append(f"    {{ {name}, {len(data)}, {c['crc']} }}")
    ap("static const vec_crc_t VEC_CRC[] = {")
    ap(",\n".join(crc_entries))
    ap("};")
    ap(f"#define VEC_CRC_COUNT {len(crc_entries)}")
    ap("")

    # ---------- v1 key/nonce/aad ----------
    ap("typedef struct {")
    ap("    uint16_t cmd;")
    ap("    uint16_t tid;")
    ap("    const uint8_t *key;")
    ap("    const uint8_t *nonce;")
    ap("    const uint8_t *aad;")
    ap("} vec_v1_key_t;")
    ap("")
    v1k_entries = []
    for i, c in enumerate(j["v1_key_nonce_aad"]):
        kname = f"vec_v1k{i}_key"
        nname = f"vec_v1k{i}_nonce"
        aname = f"vec_v1k{i}_aad"
        ap(c_bytes(kname, bytes.fromhex(c["key_hex"])))
        ap(c_bytes(nname, bytes.fromhex(c["nonce_hex"])))
        ap(c_bytes(aname, bytes.fromhex(c["aad_hex"])))
        v1k_entries.append(
            f"    {{ {c['cmd']}, {c['tid']}, {kname}, {nname}, {aname} }}"
        )
    ap("static const vec_v1_key_t VEC_V1_KEYS[] = {")
    ap(",\n".join(v1k_entries))
    ap("};")
    ap(f"#define VEC_V1_KEYS_COUNT {len(v1k_entries)}")
    ap("")

    # ---------- v1 frames ----------
    ap("typedef struct {")
    ap("    uint16_t cmd;")
    ap("    uint16_t tid;")
    ap("    const uint8_t *pt;")
    ap("    size_t pt_len;")
    ap("    const uint8_t *frame;")
    ap("    size_t frame_len;")
    ap("    uint16_t crc;")
    ap("} vec_v1_frame_t;")
    ap("")
    v1f_entries = []
    for i, c in enumerate(j["v1_frames"]):
        pname = f"vec_v1f{i}_pt"
        fname = f"vec_v1f{i}_frame"
        pt = bytes.fromhex(c["plaintext_hex"])
        frm = bytes.fromhex(c["frame_hex"])
        ap(c_bytes(pname, pt))
        ap(c_bytes(fname, frm))
        v1f_entries.append(
            f"    {{ {c['cmd']}, {c['tid']}, {pname}, {len(pt)}, "
            f"{fname}, {len(frm)}, {c['crc']} }}"
        )
    ap("static const vec_v1_frame_t VEC_V1_FRAMES[] = {")
    ap(",\n".join(v1f_entries))
    ap("};")
    ap(f"#define VEC_V1_FRAMES_COUNT {len(v1f_entries)}")
    ap("")

    # ---------- v0 key/iv ----------
    ap("typedef struct {")
    ap("    uint16_t cmd;")
    ap("    uint16_t tid;")
    ap("    const uint8_t *key;")
    ap("    const uint8_t *iv;")
    ap("} vec_v0_key_t;")
    ap("")
    v0k_entries = []
    for i, c in enumerate(j["v0_key_iv"]):
        kname = f"vec_v0k{i}_key"
        iname = f"vec_v0k{i}_iv"
        ap(c_bytes(kname, bytes.fromhex(c["key_hex"])))
        ap(c_bytes(iname, bytes.fromhex(c["iv_hex"])))
        v0k_entries.append(f"    {{ {c['cmd']}, {c['tid']}, {kname}, {iname} }}")
    ap("static const vec_v0_key_t VEC_V0_KEYS[] = {")
    ap(",\n".join(v0k_entries))
    ap("};")
    ap(f"#define VEC_V0_KEYS_COUNT {len(v0k_entries)}")
    ap("")

    # ---------- v0 frames ----------
    ap("typedef struct {")
    ap("    uint16_t cmd;")
    ap("    uint16_t tid;")
    ap("    const uint8_t *pt;")
    ap("    size_t pt_len;")
    ap("    const uint8_t *frame;")
    ap("    size_t frame_len;")
    ap("} vec_v0_frame_t;")
    ap("")
    v0f_entries = []
    for i, c in enumerate(j["v0_frames"]):
        pname = f"vec_v0f{i}_pt"
        fname = f"vec_v0f{i}_frame"
        pt = bytes.fromhex(c["plaintext_hex"])
        frm = bytes.fromhex(c["frame_hex"])
        ap(c_bytes(pname, pt))
        ap(c_bytes(fname, frm))
        v0f_entries.append(
            f"    {{ {c['cmd']}, {c['tid']}, {pname}, {len(pt)}, "
            f"{fname}, {len(frm)} }}"
        )
    ap("static const vec_v0_frame_t VEC_V0_FRAMES[] = {")
    ap(",\n".join(v0f_entries))
    ap("};")
    ap(f"#define VEC_V0_FRAMES_COUNT {len(v0f_entries)}")
    ap("")

    ap("#endif /* HIFLOW_TEST_VECTORS_H */")
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    here = Path(__file__).resolve().parent
    src = Path(argv[1]) if len(argv) > 1 else here / "vectors.json"
    dst = Path(argv[2]) if len(argv) > 2 else here / "host" / "vectors.h"

    with src.open("r", encoding="utf-8") as fh:
        j = json.load(fh)

    dst.parent.mkdir(parents=True, exist_ok=True)
    text = emit(j)
    with dst.open("w", encoding="utf-8") as fh:
        fh.write(text)

    print(f"wrote {dst} ({len(text)} bytes) from {src}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
