/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.2 */

#ifndef PB_APPINFOMATIONDATA_PB_H_INCLUDED
#define PB_APPINFOMATIONDATA_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(16) APPDtuInfoMO_enc_rand_t;
typedef struct _APPDtuInfoMO {
    int32_t device_kind; /* Type of the device */
    int32_t dtu_sw_version; /* DTU software version */
    int32_t dtu_hw_version; /* DTU hardware version */
    int32_t dtu_step_time; /* DTU step time */
    int32_t dtu_rf_hw_version; /* DTU RF hardware version */
    int32_t dtu_rf_sw_version; /* DTU RF software version */
    int32_t access_model; /* Access model */
    int32_t communication_time; /* Communication time */
    int32_t signal_strength; /* Signal strength */
    pb_callback_t gprs_version; /* GPRS version */
    pb_callback_t wifi_version; /* Wifi version */
    pb_callback_t ka_number; /* KA number */
    int32_t dtu_rule_id; /* DTU rule ID */
    int32_t dtu_error_code; /* DTU error code */
    int32_t dtu485_mode; /* DTU485 mode */
    int32_t dtu485_address; /* DTU485 address */
    int32_t sub1g_frequency_band; /* Sub1G frequency band */
    int32_t sub1g_channel_total_number; /* Sub1G channel total number */
    int32_t sub1g_channel_number; /* Sub1G channel number */
    int32_t sub1g_rp; /* Sub1G RP */
    int32_t sub1g_channel_total; /* Sub1G channel total */
    pb_callback_t gprs_imei; /* GPRS IMEI */
    int32_t dtu_swb_time;
    int64_t dfs;
    pb_callback_t shls;
    int32_t type;
    APPDtuInfoMO_enc_rand_t enc_rand;
} APPDtuInfoMO;

typedef struct _APPMeterInfoMO {
    int32_t device_kind; /* Type of the device */
    int64_t meter_serial_number; /* Meter serial number */
    int32_t meter_model; /* Meter model */
    int32_t meter_ct; /* Meter current transformer */
    int32_t communication_way; /* Communication way */
    int32_t access_mode; /* Access mode */
    int32_t sw_version; /* Software version */
    pb_callback_t meter_value; /* Meter value */
} APPMeterInfoMO;

typedef struct _APPRpInfoMO {
    int32_t device_kind; /* Type of the device */
    int64_t rp_serial_number; /* RP serial number */
    int32_t rp_sw_version; /* RP software version */
    int32_t rp_hw_version; /* RP hardware version */
    int32_t rp_rule_id; /* RP rule ID */
} APPRpInfoMO;

typedef struct _APPPvInfoMO {
    int32_t device_kind; /* Type of the device */
    int64_t pv_serial_number; /* PV serial number */
    int32_t pv_usfw; /* PV US firmware */
    int32_t pv_sw_version; /* PV software version */
    int32_t pv_hw_part_number; /* PV hardware part number */
    int32_t pv_hw_version; /* PV hardware version */
    int32_t pv_grid_profile_code; /* PV grid profile code */
    int32_t pv_grid_profile; /* PV grid profile */
    int32_t pv_rf_hw_version; /* PV RF hardware version */
    int32_t pv_rf_sw_version; /* PV RF software version */
    int32_t mi_rule_id; /* MI rule ID */
} APPPvInfoMO;

typedef struct _APPFeatureMO {
    int32_t key; /* Feature key */
    pb_callback_t value; /* Feature value */
} APPFeatureMO;

typedef struct _APPInfoDataReqDTO {
    pb_callback_t dtu_serial_number; /* DTU serial number */
    uint32_t timestamp; /* Timestamp */
    int32_t device_number; /* Device number */
    int32_t pv_number; /* PV number */
    int32_t package_number; /* Package number */
    int32_t current_package; /* Current package */
    int32_t channel; /* Channel */
    bool has_dtu_info;
    APPDtuInfoMO dtu_info; /* DTU information */
    pb_callback_t meter_info; /* Meter information */
    pb_callback_t rp_info; /* RP information */
    pb_callback_t pv_info; /* PV information */
    uint32_t unknown_field; /* Unknown field */
    pb_callback_t app_features; /* Application features */
} APPInfoDataReqDTO;

typedef PB_BYTES_ARRAY_T(24) APPInfoDataResDTO_time_ymd_hms_t;
typedef struct _APPInfoDataResDTO {
    APPInfoDataResDTO_time_ymd_hms_t time_ymd_hms; /* Date and time */
    int32_t offset; /* Offset */
    int32_t current_package; /* Current package */
    int32_t error_code; /* Error code */
    uint32_t time; /* Timestamp */
} APPInfoDataResDTO;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define APPDtuInfoMO_init_default                {0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, 0, {0, {0}}}
#define APPMeterInfoMO_init_default              {0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}}
#define APPRpInfoMO_init_default                 {0, 0, 0, 0, 0}
#define APPPvInfoMO_init_default                 {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define APPFeatureMO_init_default                {0, {{NULL}, NULL}}
#define APPInfoDataReqDTO_init_default           {{{NULL}, NULL}, 0, 0, 0, 0, 0, 0, false, APPDtuInfoMO_init_default, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define APPInfoDataResDTO_init_default           {{0, {0}}, 0, 0, 0, 0}
#define APPDtuInfoMO_init_zero                   {0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}, 0, {0, {0}}}
#define APPMeterInfoMO_init_zero                 {0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}}
#define APPRpInfoMO_init_zero                    {0, 0, 0, 0, 0}
#define APPPvInfoMO_init_zero                    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define APPFeatureMO_init_zero                   {0, {{NULL}, NULL}}
#define APPInfoDataReqDTO_init_zero              {{{NULL}, NULL}, 0, 0, 0, 0, 0, 0, false, APPDtuInfoMO_init_zero, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}}
#define APPInfoDataResDTO_init_zero              {{0, {0}}, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define APPDtuInfoMO_device_kind_tag             1
#define APPDtuInfoMO_dtu_sw_version_tag          2
#define APPDtuInfoMO_dtu_hw_version_tag          3
#define APPDtuInfoMO_dtu_step_time_tag           4
#define APPDtuInfoMO_dtu_rf_hw_version_tag       5
#define APPDtuInfoMO_dtu_rf_sw_version_tag       6
#define APPDtuInfoMO_access_model_tag            7
#define APPDtuInfoMO_communication_time_tag      8
#define APPDtuInfoMO_signal_strength_tag         9
#define APPDtuInfoMO_gprs_version_tag            10
#define APPDtuInfoMO_wifi_version_tag            11
#define APPDtuInfoMO_ka_number_tag               12
#define APPDtuInfoMO_dtu_rule_id_tag             13
#define APPDtuInfoMO_dtu_error_code_tag          14
#define APPDtuInfoMO_dtu485_mode_tag             15
#define APPDtuInfoMO_dtu485_address_tag          16
#define APPDtuInfoMO_sub1g_frequency_band_tag    17
#define APPDtuInfoMO_sub1g_channel_total_number_tag 18
#define APPDtuInfoMO_sub1g_channel_number_tag    19
#define APPDtuInfoMO_sub1g_rp_tag                20
#define APPDtuInfoMO_sub1g_channel_total_tag     21
#define APPDtuInfoMO_gprs_imei_tag               22
#define APPDtuInfoMO_dtu_swb_time_tag            23
#define APPDtuInfoMO_dfs_tag                     24
#define APPDtuInfoMO_shls_tag                    25
#define APPDtuInfoMO_type_tag                    26
#define APPDtuInfoMO_enc_rand_tag                27
#define APPMeterInfoMO_device_kind_tag           1
#define APPMeterInfoMO_meter_serial_number_tag   2
#define APPMeterInfoMO_meter_model_tag           3
#define APPMeterInfoMO_meter_ct_tag              4
#define APPMeterInfoMO_communication_way_tag     5
#define APPMeterInfoMO_access_mode_tag           6
#define APPMeterInfoMO_sw_version_tag            7
#define APPMeterInfoMO_meter_value_tag           8
#define APPRpInfoMO_device_kind_tag              1
#define APPRpInfoMO_rp_serial_number_tag         2
#define APPRpInfoMO_rp_sw_version_tag            3
#define APPRpInfoMO_rp_hw_version_tag            4
#define APPRpInfoMO_rp_rule_id_tag               5
#define APPPvInfoMO_device_kind_tag              1
#define APPPvInfoMO_pv_serial_number_tag         2
#define APPPvInfoMO_pv_usfw_tag                  3
#define APPPvInfoMO_pv_sw_version_tag            4
#define APPPvInfoMO_pv_hw_part_number_tag        5
#define APPPvInfoMO_pv_hw_version_tag            6
#define APPPvInfoMO_pv_grid_profile_code_tag     7
#define APPPvInfoMO_pv_grid_profile_tag          8
#define APPPvInfoMO_pv_rf_hw_version_tag         9
#define APPPvInfoMO_pv_rf_sw_version_tag         10
#define APPPvInfoMO_mi_rule_id_tag               11
#define APPFeatureMO_key_tag                     1
#define APPFeatureMO_value_tag                   2
#define APPInfoDataReqDTO_dtu_serial_number_tag  1
#define APPInfoDataReqDTO_timestamp_tag          2
#define APPInfoDataReqDTO_device_number_tag      3
#define APPInfoDataReqDTO_pv_number_tag          4
#define APPInfoDataReqDTO_package_number_tag     5
#define APPInfoDataReqDTO_current_package_tag    6
#define APPInfoDataReqDTO_channel_tag            7
#define APPInfoDataReqDTO_dtu_info_tag           8
#define APPInfoDataReqDTO_meter_info_tag         9
#define APPInfoDataReqDTO_rp_info_tag            10
#define APPInfoDataReqDTO_pv_info_tag            11
#define APPInfoDataReqDTO_unknown_field_tag      12
#define APPInfoDataReqDTO_app_features_tag       13
#define APPInfoDataResDTO_time_ymd_hms_tag       1
#define APPInfoDataResDTO_offset_tag             2
#define APPInfoDataResDTO_current_package_tag    3
#define APPInfoDataResDTO_error_code_tag         4
#define APPInfoDataResDTO_time_tag               5

/* Struct field encoding specification for nanopb */
#define APPDtuInfoMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    device_kind,       1) \
X(a, STATIC,   SINGULAR, INT32,    dtu_sw_version,    2) \
X(a, STATIC,   SINGULAR, INT32,    dtu_hw_version,    3) \
X(a, STATIC,   SINGULAR, INT32,    dtu_step_time,     4) \
X(a, STATIC,   SINGULAR, INT32,    dtu_rf_hw_version,   5) \
X(a, STATIC,   SINGULAR, INT32,    dtu_rf_sw_version,   6) \
X(a, STATIC,   SINGULAR, INT32,    access_model,      7) \
X(a, STATIC,   SINGULAR, INT32,    communication_time,   8) \
X(a, STATIC,   SINGULAR, INT32,    signal_strength,   9) \
X(a, CALLBACK, SINGULAR, STRING,   gprs_version,     10) \
X(a, CALLBACK, SINGULAR, STRING,   wifi_version,     11) \
X(a, CALLBACK, SINGULAR, STRING,   ka_number,        12) \
X(a, STATIC,   SINGULAR, INT32,    dtu_rule_id,      13) \
X(a, STATIC,   SINGULAR, INT32,    dtu_error_code,   14) \
X(a, STATIC,   SINGULAR, INT32,    dtu485_mode,      15) \
X(a, STATIC,   SINGULAR, INT32,    dtu485_address,   16) \
X(a, STATIC,   SINGULAR, INT32,    sub1g_frequency_band,  17) \
X(a, STATIC,   SINGULAR, INT32,    sub1g_channel_total_number,  18) \
X(a, STATIC,   SINGULAR, INT32,    sub1g_channel_number,  19) \
X(a, STATIC,   SINGULAR, INT32,    sub1g_rp,         20) \
X(a, STATIC,   SINGULAR, INT32,    sub1g_channel_total,  21) \
X(a, CALLBACK, SINGULAR, STRING,   gprs_imei,        22) \
X(a, STATIC,   SINGULAR, INT32,    dtu_swb_time,     23) \
X(a, STATIC,   SINGULAR, INT64,    dfs,              24) \
X(a, CALLBACK, REPEATED, INT64,    shls,             25) \
X(a, STATIC,   SINGULAR, INT32,    type,             26) \
X(a, STATIC,   SINGULAR, BYTES,    enc_rand,         27)
#define APPDtuInfoMO_CALLBACK pb_default_field_callback
#define APPDtuInfoMO_DEFAULT NULL

#define APPMeterInfoMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    device_kind,       1) \
X(a, STATIC,   SINGULAR, INT64,    meter_serial_number,   2) \
X(a, STATIC,   SINGULAR, INT32,    meter_model,       3) \
X(a, STATIC,   SINGULAR, INT32,    meter_ct,          4) \
X(a, STATIC,   SINGULAR, INT32,    communication_way,   5) \
X(a, STATIC,   SINGULAR, INT32,    access_mode,       6) \
X(a, STATIC,   SINGULAR, INT32,    sw_version,        7) \
X(a, CALLBACK, SINGULAR, STRING,   meter_value,       8)
#define APPMeterInfoMO_CALLBACK pb_default_field_callback
#define APPMeterInfoMO_DEFAULT NULL

#define APPRpInfoMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    device_kind,       1) \
X(a, STATIC,   SINGULAR, INT64,    rp_serial_number,   2) \
X(a, STATIC,   SINGULAR, INT32,    rp_sw_version,     3) \
X(a, STATIC,   SINGULAR, INT32,    rp_hw_version,     4) \
X(a, STATIC,   SINGULAR, INT32,    rp_rule_id,        5)
#define APPRpInfoMO_CALLBACK NULL
#define APPRpInfoMO_DEFAULT NULL

#define APPPvInfoMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    device_kind,       1) \
X(a, STATIC,   SINGULAR, INT64,    pv_serial_number,   2) \
X(a, STATIC,   SINGULAR, INT32,    pv_usfw,           3) \
X(a, STATIC,   SINGULAR, INT32,    pv_sw_version,     4) \
X(a, STATIC,   SINGULAR, INT32,    pv_hw_part_number,   5) \
X(a, STATIC,   SINGULAR, INT32,    pv_hw_version,     6) \
X(a, STATIC,   SINGULAR, INT32,    pv_grid_profile_code,   7) \
X(a, STATIC,   SINGULAR, INT32,    pv_grid_profile,   8) \
X(a, STATIC,   SINGULAR, INT32,    pv_rf_hw_version,   9) \
X(a, STATIC,   SINGULAR, INT32,    pv_rf_sw_version,  10) \
X(a, STATIC,   SINGULAR, INT32,    mi_rule_id,       11)
#define APPPvInfoMO_CALLBACK NULL
#define APPPvInfoMO_DEFAULT NULL

#define APPFeatureMO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define APPFeatureMO_CALLBACK pb_default_field_callback
#define APPFeatureMO_DEFAULT NULL

#define APPInfoDataReqDTO_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   dtu_serial_number,   1) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         2) \
X(a, STATIC,   SINGULAR, INT32,    device_number,     3) \
X(a, STATIC,   SINGULAR, INT32,    pv_number,         4) \
X(a, STATIC,   SINGULAR, INT32,    package_number,    5) \
X(a, STATIC,   SINGULAR, INT32,    current_package,   6) \
X(a, STATIC,   SINGULAR, INT32,    channel,           7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  dtu_info,          8) \
X(a, CALLBACK, REPEATED, MESSAGE,  meter_info,        9) \
X(a, CALLBACK, REPEATED, MESSAGE,  rp_info,          10) \
X(a, CALLBACK, REPEATED, MESSAGE,  pv_info,          11) \
X(a, STATIC,   SINGULAR, UINT32,   unknown_field,    12) \
X(a, CALLBACK, REPEATED, MESSAGE,  app_features,     13)
#define APPInfoDataReqDTO_CALLBACK pb_default_field_callback
#define APPInfoDataReqDTO_DEFAULT NULL
#define APPInfoDataReqDTO_dtu_info_MSGTYPE APPDtuInfoMO
#define APPInfoDataReqDTO_meter_info_MSGTYPE APPMeterInfoMO
#define APPInfoDataReqDTO_rp_info_MSGTYPE APPRpInfoMO
#define APPInfoDataReqDTO_pv_info_MSGTYPE APPPvInfoMO
#define APPInfoDataReqDTO_app_features_MSGTYPE APPFeatureMO

#define APPInfoDataResDTO_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    time_ymd_hms,      1) \
X(a, STATIC,   SINGULAR, INT32,    offset,            2) \
X(a, STATIC,   SINGULAR, INT32,    current_package,   3) \
X(a, STATIC,   SINGULAR, INT32,    error_code,        4) \
X(a, STATIC,   SINGULAR, UINT32,   time,              5)
#define APPInfoDataResDTO_CALLBACK NULL
#define APPInfoDataResDTO_DEFAULT NULL

extern const pb_msgdesc_t APPDtuInfoMO_msg;
extern const pb_msgdesc_t APPMeterInfoMO_msg;
extern const pb_msgdesc_t APPRpInfoMO_msg;
extern const pb_msgdesc_t APPPvInfoMO_msg;
extern const pb_msgdesc_t APPFeatureMO_msg;
extern const pb_msgdesc_t APPInfoDataReqDTO_msg;
extern const pb_msgdesc_t APPInfoDataResDTO_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define APPDtuInfoMO_fields &APPDtuInfoMO_msg
#define APPMeterInfoMO_fields &APPMeterInfoMO_msg
#define APPRpInfoMO_fields &APPRpInfoMO_msg
#define APPPvInfoMO_fields &APPPvInfoMO_msg
#define APPFeatureMO_fields &APPFeatureMO_msg
#define APPInfoDataReqDTO_fields &APPInfoDataReqDTO_msg
#define APPInfoDataResDTO_fields &APPInfoDataResDTO_msg

/* Maximum encoded size of messages (where known) */
/* APPDtuInfoMO_size depends on runtime parameters */
/* APPMeterInfoMO_size depends on runtime parameters */
/* APPFeatureMO_size depends on runtime parameters */
/* APPInfoDataReqDTO_size depends on runtime parameters */
#define APPINFOMATIONDATA_PB_H_MAX_SIZE          APPPvInfoMO_size
#define APPInfoDataResDTO_size                   65
#define APPPvInfoMO_size                         121
#define APPRpInfoMO_size                         55

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
