#!/usr/bin/env python3
"""Build-time helper: test/vectors.json -> test/host/vectors_proto.h

Turns the request payloads, the device status replies and the paged RealDataNew
reply from test/vectors.json (produced with the unmodified Python library, see
test/gen_vectors.py) into C literals, so test_proto.c can compare the encoders
byte by byte against the reference.

Only the Python standard library is used.

Usage: gen_proto_header.py <vectors.json> <out.h>
"""
import json
import sys


def c_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "\\r")
    return '"%s"' % escaped


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    src, dst = sys.argv[1], sys.argv[2]

    with open(src, encoding="utf-8") as fh:
        data = json.load(fh)

    req = data["request_payloads"]
    if "error" in req:
        print("vectors.json carries no request payloads: %s" % req["error"], file=sys.stderr)
        return 1
    replies = data["status_replies"]
    pages = data["protobuf_realdata_new_pages"]
    merged = pages["merged"]

    out = []
    out.append("/* AUTO-GENERATED by gen_proto_header.py from %s\n" % src)
    out.append(" * Request payloads, status replies and the paged reply (ground truth).\n")
    out.append(" * DO NOT EDIT. */\n")
    out.append("#ifndef VECTORS_PROTO_H\n#define VECTORS_PROTO_H\n\n#include <stdint.h>\n\n")

    out.append("#define VEC_REQ_TIME ((int64_t) %d)\n" % req["time"])
    out.append("#define VEC_REQ_OFFSET %d\n" % req["offset"])
    out.append("#define VEC_REQ_YMD %s\n" % c_string(req["time_ymd_hms"]))
    out.append("#define VEC_BLE_ID %s\n" % c_string(req["ble_id"]))
    out.append("#define VEC_PIN %s\n" % c_string(req["pin"]))
    out.append("#define VEC_TIME_SYNC_DATA %s\n\n" % c_string(req["time_sync"]["data"]))

    hexes = [
        ("VEC_HEX_LOGIN", req["login"]["hex"]),
        ("VEC_HEX_PIN", req["pin_cmd"]["hex"]),
        ("VEC_HEX_TIME_SYNC", req["time_sync"]["hex"]),
        ("VEC_HEX_POLL_LOGIN", req["status_poll"]["64"]),
        ("VEC_HEX_POLL_PIN", req["status_poll"]["82"]),
        ("VEC_HEX_POLL_TIME_SYNC", req["status_poll"]["104"]),
        ("VEC_HEX_REAL_DATA_CP0", req["real_data_new"]["cp0_hex"]),
        ("VEC_HEX_REAL_DATA_CP1", req["real_data_new"]["cp1_hex"]),
        ("VEC_HEX_APP_INFO_V0", req["app_info_v0"]["hex"]),
        ("VEC_HEX_PAGE0", pages["page0_hex"]),
        ("VEC_HEX_PAGE1", pages["page1_hex"]),
        ("VEC_HEX_PAGE_SINGLE", pages["single_page_hex"]),
    ]
    for name, value in hexes:
        out.append("static const char %s[] = \"%s\";\n" % (name, value))

    out.append("\n#define VEC_STATUS_REPLY_COUNT %d\n" % len(replies))
    out.append("static const struct { int action; int sts; const char *hex; } "
               "VEC_STATUS_REPLIES[] = {\n")
    for r in replies:
        out.append("    {%d, %d, \"%s\"},\n" % (r["action"], r["sts"], r["hex"]))
    out.append("};\n\n")

    out.append("#define VEC_PAGE_AP %d\n" % pages["ap"])
    out.append("#define VEC_MERGED_AC_POWER_W %.4ff\n" % merged["ac_power_w"])
    out.append("#define VEC_MERGED_AC_VOLTAGE_V %.4ff\n" % merged["ac_voltage_v"])
    out.append("#define VEC_MERGED_AC_CURRENT_A %.4ff\n" % merged["ac_current_a"])
    out.append("#define VEC_MERGED_AC_FREQUENCY_HZ %.4ff\n" % merged["ac_frequency_hz"])
    out.append("#define VEC_MERGED_TEMPERATURE_C %.4ff\n" % merged["temperature_c"])
    out.append("#define VEC_MERGED_ENERGY_TOTAL_WH %.1ff\n" % merged["energy_total_wh"])
    out.append("#define VEC_MERGED_ENERGY_DAILY_WH %.1ff\n" % merged["energy_daily_wh"])
    out.append("#define VEC_MERGED_PORT_COUNT %d\n" % len(merged["ports"]))
    out.append("static const struct { int port; float power_w; float voltage_v; float current_a; } "
               "VEC_MERGED_PORTS[] = {\n")
    for p in merged["ports"]:
        out.append("    {%d, %.4ff, %.4ff, %.4ff},\n"
                   % (p["port"], p["power_w"], p["voltage_v"], p["current_a"]))
    out.append("};\n")

    out.append("\n#endif /* VECTORS_PROTO_H */\n")

    with open(dst, "w", encoding="utf-8") as fh:
        fh.write("".join(out))
    print("wrote %s (%d request payloads, %d status replies, %d pages)"
          % (dst, len(hexes) - 2, len(replies), 2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
