#!/usr/bin/env python3
"""Build-time helper: test/vectors.json -> test/host/vectors_pb.h

The vectors in test/vectors.json are the ground truth: they were produced by
gen_vectors.py using the *real* Python protobuf modules of TheTiEr/hiflow-ble.
This script turns the expected RealDataNew field values into C arrays so the
host test can compare nanopb's decode result against them.

Only the Python standard library is used (json). The wire bytes themselves are
NOT baked in here: test_pb.c reads `wire_hex` from vectors.json at run time.

Usage: gen_vectors_header.py <vectors.json> <out.h>
"""
import json
import sys


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    src, dst = sys.argv[1], sys.argv[2]

    with open(src, encoding="utf-8") as fh:
        data = json.load(fh)

    pbn = data["protobuf_realdata_new"]
    fields = pbn["fields"]
    sgs = fields["sgs_data"]
    pv = fields["pv_data"]

    def arr(name: str, vals) -> str:
        body = ", ".join(str(v) for v in vals)
        return "static const int64_t %s[] = {%s};\n" % (name, body)

    out = []
    out.append("/* AUTO-GENERATED by gen_vectors_header.py from %s\n" % src)
    out.append(" * Expected RealDataNew field values (ground truth from vectors.json).\n")
    out.append(" * DO NOT EDIT. */\n")
    out.append("#ifndef VECTORS_PB_H\n#define VECTORS_PB_H\n\n#include <stdint.h>\n\n")
    out.append("#define EXP_SGS_COUNT %d\n" % len(sgs))
    out.append("#define EXP_PV_COUNT %d\n\n" % len(pv))

    for key in ("active_power", "voltage", "frequency", "temperature"):
        out.append(arr("EXP_SGS_" + key.upper(), [m[key] for m in sgs]))
    out.append("\n")
    for key in ("voltage", "current", "power", "energy_total", "energy_daily", "error_code"):
        out.append(arr("EXP_PV_" + key.upper(), [m[key] for m in pv]))

    out.append("\n/* scaling (informational, from vectors.json) */\n")
    for key, val in pbn.get("scaling", {}).items():
        out.append("/* scaling.%s = %s */\n" % (key, val))
    out.append("\n#endif /* VECTORS_PB_H */\n")

    with open(dst, "w", encoding="utf-8") as fh:
        fh.write("".join(out))
    print("wrote %s (%d sgs entry, %d pv entries)" % (dst, len(sgs), len(pv)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
