#!/usr/bin/env python3
"""Generates esp32c6-bleonly.yaml: the bridge from esp32c6.yaml without Zigbee.

Purpose: the C6 has a single 2.4 GHz radio path. If the full image drops BLE
links with reason 0x08 (supervision timeout), running the same bridge without
the Zigbee stack tells radio coexistence apart from placement or the inverter
(see docs/troubleshooting.md).

Usage: python3 tools/make_bleonly_board.py
"""
from pathlib import Path

SRC = Path(__file__).resolve().parent.parent / "esp32c6.yaml"
DST = SRC.with_name("esp32c6-bleonly.yaml")

ZIGBEE_BLOCKS = ("zigbee:",)
# Sensor options that are only valid while the zigbee component is loaded.
ZIGBEE_ONLY_OPTIONS = ("report:",)


def _indent(line: str) -> int:
    return len(line) - len(line.lstrip())


def strip_zigbee(text: str) -> str:
    lines = text.splitlines()
    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()
        # Drop the top-level zigbee block.
        if stripped in ZIGBEE_BLOCKS:
            i += 1
            while i < len(lines) and (lines[i].startswith((" ", "\t")) or not lines[i].strip()):
                i += 1
            continue
        # Drop the zigbee-only sensor options (otherwise: "This option requires
        # component zigbee"), together with the comment lines right above them.
        if stripped.startswith(ZIGBEE_ONLY_OPTIONS):
            while out and out[-1].strip().startswith("#") and _indent(out[-1]) == _indent(line):
                out.pop()
            i += 1
            continue
        out.append(line)
        i += 1
    return "\n".join(out) + "\n"


def main() -> None:
    text = SRC.read_text()
    variant = strip_zigbee(text)
    header = (
        "# GENERATED by tools/make_bleonly_board.py from esp32c6.yaml - do not edit by hand.\n"
        "# BLE-only variant: the bridge without Zigbee, isolates radio coexistence.\n"
    )
    DST.write_text(header + variant)
    print(f"{DST.name}: {len(variant.splitlines())} lines (source: {len(text.splitlines())})")
    for needle in ("hiflow_ble:", "platform: hiflow_ble", "zigbee:", "report:"):
        print(f"  {needle!r} left: {variant.count(needle)}")


if __name__ == "__main__":
    main()
