#!/usr/bin/env python3
"""Generates hiflow-zb-bleonly.yaml: the bridge from hiflow-zb.yaml without Zigbee.

Purpose: the C6 has a single 2.4 GHz radio path. If the full image drops BLE
links with reason 0x08 (supervision timeout), running the same bridge without
the Zigbee stack tells radio coexistence apart from placement or the inverter
(see docs/troubleshooting.md).

Usage: python3 tools/make_bleonly_board.py
"""
from pathlib import Path

SRC = Path(__file__).resolve().parent.parent / "hiflow-zb.yaml"
DST = SRC.with_name("hiflow-zb-bleonly.yaml")

ZIGBEE_BLOCKS = ("zigbee:", "zigbee_ota:", "zigbee_power:")
# Blocks a board file may add to as well (the Waveshare BOOT button lives in
# zigbee_power): left as `!remove`, which also drops what a package brings in.
REMOVED_BLOCKS = ("zigbee_power:",)
# Sensor options that are only valid while the zigbee component is loaded.
ZIGBEE_ONLY_OPTIONS = ("report:", "endpoint:")
# A list entry that reads zigbee_power goes with it.
ZIGBEE_POWER_REF = "id(zb_power)"


def _indent(line: str) -> int:
    return len(line) - len(line.lstrip())


def strip_zigbee(text: str) -> str:
    lines = text.splitlines()
    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()
        # Drop the top-level zigbee blocks, together with the comment lines
        # right above them.
        if stripped in ZIGBEE_BLOCKS:
            while out and out[-1].startswith("#"):
                out.pop()
            i += 1
            while i < len(lines) and (lines[i].startswith((" ", "\t")) or not lines[i].strip()):
                i += 1
            if stripped in REMOVED_BLOCKS:
                out.append(f"{stripped} !remove")
                out.append("")
            continue
        # Drop a list entry that needs zigbee_power (a template sensor on
        # id(zb_power)), together with the comment lines right above it.
        if stripped.startswith("- "):
            end = i + 1
            while end < len(lines) and (_indent(lines[end]) > _indent(line) or not lines[end].strip()):
                end += 1
            if any(ZIGBEE_POWER_REF in item for item in lines[i:end]):
                while out and out[-1].strip().startswith("#") and _indent(out[-1]) == _indent(line):
                    out.pop()
                while out and not out[-1].strip():
                    out.pop()
                out.append("")
                i = end
                continue
        # Drop the zigbee-only sensor options (otherwise: "This option requires
        # component zigbee"), together with the comment lines right above them.
        if stripped.startswith(ZIGBEE_ONLY_OPTIONS):
            while out and out[-1].strip().startswith("#") and _indent(out[-1]) == _indent(line):
                out.pop()
            i += 1
            continue
        out.append(line)
        i += 1
    while out and not out[-1].strip():
        out.pop()
    return "\n".join(out) + "\n"


def main() -> None:
    text = SRC.read_text()
    variant = strip_zigbee(text)
    header = (
        "# GENERATED by tools/make_bleonly_board.py from hiflow-zb.yaml - do not edit by hand.\n"
        "# BLE-only variant: the bridge without Zigbee, isolates radio coexistence.\n"
    )
    DST.write_text(header + variant)
    print(f"{DST.name}: {len(variant.splitlines())} lines (source: {len(text.splitlines())})")
    for needle in ("hiflow_ble:", "platform: hiflow_ble", "zigbee:", "report:", ZIGBEE_POWER_REF):
        print(f"  {needle!r} left: {variant.count(needle)}")


if __name__ == "__main__":
    main()
